export const OPEN_CLOSE_CART = "OPEN_CLOSE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const SEARCH_BOOKS = "SEARCH_BOOKS";
